version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Generate coverage report
          command: npm run test:ci
      - store_artifacts: # Save tests results as artifacts
          path: test-results.xml
          prefix: tests
      - store_artifacts: # Save coverage reports as artifacts
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
          

workflows:
  build_test:
    jobs:
      - test
